// SwiftDM 嗅探规则 —— 纯函数集合，service worker / content script / Node 测试共用。
// 修改这里必须同步跑 node tests/test_sniff.js。
(function (root) {
  const MANIFEST_EXT = /\.(m3u8|mpd|f4m|ism)(\?|$)/i;
  const FRAGMENT_RE = /\.(ts|m4s|mp2t)(\?|$)/i;
  const VIDEO_CT_RE = /^(video|audio)\//i;
  const HLS_CT_RE = /^application\/(vnd\.apple\.mpegurl|x-mpegurl|mpegurl)/i;
  const DASH_CT_RE = /^application\/dash\+xml/i;

  const fragState = new Map(); // tabId -> { first: ts, urls: Set, fired: Set }
  const FRAGMENT_WINDOW = 10000;
  const FRAGMENT_THRESHOLD = 5;

  function pathOf(url) {
    try { return new URL(url).pathname.toLowerCase(); } catch (e) { return ""; }
  }

  function isMseUrl(url) {
    return typeof url === "string" && /^(blob:|mediastream:)/i.test(url);
  }

  function qualityFromUrl(url) {
    const m = (url || "").toLowerCase().match(/(2160|1440|1080|720|480|360|240)p?[_\-.\/]/);
    return m ? m[1] + "P" : "";
  }

  function classifyResource(details) {
    const url = (details && details.url) || "";
    if (!url || isMseUrl(url)) return null;
    if (details.status && details.status >= 400) return null;
    const ct = ((details.contentType || "") + "").toLowerCase();
    const cd = ((details.contentDisposition || "") + "").toLowerCase();
    // attachment 属于普通文件下载，走 capture 通道（多段加速），不当媒体嗅探结果
    if (cd.indexOf("attachment") >= 0) return null;
    const path = pathOf(url);
    let kind = null;
    if (HLS_CT_RE.test(ct) || /\.m3u8(\?|$)/i.test(path)) kind = "hls";
    else if (DASH_CT_RE.test(ct) || /\.mpd(\?|$)/i.test(path)) kind = "dash";
    else if (FRAGMENT_RE.test(path) && !/mpegurl|dash/.test(ct)) return null; // 分片交给 noteFragment
    else if (VIDEO_CT_RE.test(ct) && !/mpegurl|dash|mp2t/.test(ct)) kind = "video";
    if (!kind) return null;
    return {
      url: url,
      kind: kind,
      quality_hint: qualityFromUrl(url),
      bytes: Number(details.contentLength || 0) || 0,
      is_mse: false,
    };
  }

  function noteFragment(tabId, url) {
    if (!url || !FRAGMENT_RE.test(pathOf(url))) return null;
    const key = String(tabId);
    const now = Date.now();
    let st = fragState.get(key);
    if (!st || now - st.first > FRAGMENT_WINDOW) {
      st = { first: now, urls: new Set(), fired: new Set() };
      fragState.set(key, st);
    }
    if (st.urls.has(url)) return null;
    st.urls.add(url);
    if (st.urls.size < FRAGMENT_THRESHOLD) return null;
    const signature = Array.from(st.urls).sort().join("|");
    if (st.fired.has(signature)) return null;
    st.fired.add(signature);
    // 清单没被看见（播放器用了加密清单 / Service Worker 内部拉流），只能给出「有多少分片」这一事实。
    // kind 用 hls_segments 明确标成不可下载，避免用户点下去拿到一个孤零零的 .ts。
    return {
      url: url,
      kind: "hls_segments",
      quality_hint: st.urls.size + " 个分片",
      bytes: 0,
      is_mse: false,
    };
  }

  function resetTab(tabId) {
    fragState.delete(String(tabId));
  }

  function cookiesToNetscape(cookies, pageUrl) {
    let host = "";
    try { host = new URL(pageUrl).hostname.toLowerCase(); } catch (e) { return ""; }
    const out = ["# Netscape HTTP Cookie File", "# Generated by SwiftDM", ""];
    for (const c of cookies || []) {
      if (!c || !c.name) continue;
      const bare = String(c.domain || "").replace(/^\./, "").toLowerCase();
      if (!bare) continue;
      if (!(host === bare || host.endsWith("." + bare))) continue;   // 作用域不相关的 Cookie 一律不带
      const domain = String(c.domain).startsWith(".") ? "." + bare : bare;
      const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
      const secure = c.secure ? "TRUE" : "FALSE";
      const expiry = Number(c.expirationDate || 0) | 0;
      const prefix = c.httpOnly ? "#HttpOnly_" : "";
      const value = c.value === undefined || c.value === null ? "" : String(c.value);
      out.push(prefix + [domain, flag, c.path || "/", secure, String(expiry), c.name, value].join("\t"));
    }
    return out.join("\n") + "\n";
  }

  const api = {
    MANIFEST_EXT, classifyResource, noteFragment, resetTab,
    cookiesToNetscape, isMseUrl, qualityFromUrl,
  };
  root.SwiftDMSniff = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
